### ISSUE TITLE
Custom Training for autocomplete

### ISSUE THREAD

**Issue by mihir135** [guruyuga/gurunudi#7]
Thank you for this awesome repository.

I have one question, does this repository provides custom model training for autocomplete?

Or are there any alternatives to do so?

Thanks and Regards.

**Comment by gurudevrao** [comment]
The library is currently in beta release for internal testing and the initial public release is expected by August 15 2020.

Yes, we will also be providing option to train custom models using your own data for all API calls including autocomplete.
